name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cpacademy:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd ~/cpacademy || mkdir ~/cpacademy && cd ~/cpacademy
            # Créer/mettre à jour docker-compose.yml
            cat > docker-compose.yml <<EOF
            version: '3.8'
            services:
              cpacademy:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/cpacademy:latest
                container_name: cpacademy
                ports:
                  - "3000:80"
                restart: unless-stopped
            EOF
            docker compose down
            docker compose pull
            docker compose up -d
